services:
  - type: web
    name: properchy
    env: python
    buildCommand: "pip install -r web_requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
